<?php

namespace AppBundle\Repository;

/**
 * EnCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
