<?php

namespace AppBundle\Repository;

/**
 * LignesCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignesCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
