<?php

namespace AppBundle\Repository;

/**
 * PasswordUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordUpdateRepository extends \Doctrine\ORM\EntityRepository
{
}
